# This file holds the settings for the self watering plant display.
# This includes feed tube configurations and watering tasks.

# This file must follow the following format:
# Feeds:
#   ## Feed Tube 0 ##
#   - RaspberryPiGPIO: [VALUE]
#     Tasks:
        ### Task 0 ###
#       - TimeOfDay: [VALUE]
#         mL: [VALUE]
#         DaySkip: [VALUE]
        ### Task 1 ###
#       ...etc...
#   ## Feed Tube 1 ##
#   ...etc...

# Important notes:
# * If a tube has no tasks, exclude "Tasks:" from it's members
# * Each tube must include a RaspberryPiGPIO value of int type.
# * Each task must include:
#   - TimeOfDay
#   - mL
#   - DaySkip (int)

Feeds:
    # Feed Tube 0
    - RaspberryPiGPIO: 32
      Tasks:
          ### Task 0 ###
          - TimeOfDay: 123456
            mL: 2
            DaySkip: 0
          ### Task 2 ###
          - TimeOfDay: 123456 
            mL: 2
            DaySkip: 0
            
    # Feed Tube 1
    - RaspberryPiGPIO: 36
      Tasks:
          ### Task 0 ###
          - TimeOfDay: 123456
            mL: 2
            DaySkip: 0
          ### Task 2 ###
          - TimeOfDay: 123456 
            mL: 2
            DaySkip: 0

    # Feed Tube 2
    - RaspberryPiGPIO: 38
      Tasks:
          ### Task 0 ###
          - TimeOfDay: 
            mL: 2
            DaySkip: 0
          ### Task 2 ###
          - TimeOfDay: 123456 
            mL: 2
            DaySkip: 0

    # Feed Tube 3
    - RaspberryPiGPIO: 40
